### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by ertant** [andrew-bn/RedisBoost#3]
Hi,

On some production systems I get following error and next command get hangs until timeout is occur.

	System.NullReferenceException: Object reference not set to an instance of an object.
	   at RedisBoost.Core.Channel.RedisChannel.ProcessRedisResponse(TaskCompletionSource`1 tcs, Exception ex, RedisResponse response)
	   at RedisBoost.Core.Pipeline.RedisPipeline.ItemReceiveProcessDone(Boolean async, ReceiverAsyncEventArgs args)
	   at RedisBoost.Core.Pipeline.RedisPipeline.RunReceiveProcess()
	   at RedisBoost.Core.Pipeline.RedisPipeline.ItemSendProcessDone(Boolean async, SenderAsyncEventArgs args)
	   at RedisBoost.Core.Pipeline.RedisPipeline.RunSendProcess()
	   at RedisBoost.Core.Pipeline.RedisPipeline.ExecuteCommandAsync(Byte[][] args, PipelineItem item)
	   at RedisBoost.Core.Pipeline.RedisPipeline.ExecuteCommandAsync(Byte[][] args, Action`2 callBack)
	   at RedisBoost.Core.Channel.RedisChannel.ExecuteRedisCommand(Byte[][] args)
	   at RedisBoost.Core.Channel.RedisChannel.BulkCommand(Byte[][] args)
	   at Cache.Client.Get[T](String key)

After hang, I'm able to connect with cli tool and looks like last executed command is GET

Tools\Redis>redis-cli
127.0.0.1:6379> CLIENT LIST
id=10 addr=127.0.0.1:49282 fd=13 name= age=48 idle=43 flags=N db=0 sub=0 psub=0
multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=get
id=11 addr=127.0.0.1:49284 fd=9 name= age=38 idle=38 flags=N db=0 sub=0 psub=0 m
ulti=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=get
id=12 addr=127.0.0.1:49286 fd=10 name= age=3 idle=0 flags=N db=0 sub=0 psub=0 mu
lti=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
127.0.0.1:6379>

Client is coded like;

    var result = this.client.GetAsync(key).Result;

I have tried couple another methods but does not change the result.

Thank you

**Comment by andrew-bn** [comment]
Hi,
Thank you for bug report.
New version was released: RedisBoost 1.6.2.
